// <auto-generated />
using Catalog.Persistence.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Catalog.Persistence.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240821152937_Initialize")]
    partial class Initialize
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Catalog.Domain.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductID");

                    b.HasIndex("ProductID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            Description = "Product 1 Description",
                            Name = "Product 1",
                            Price = 61250m
                        },
                        new
                        {
                            ProductID = 2,
                            Description = "Product 2 Description",
                            Name = "Product 2",
                            Price = 89444m
                        },
                        new
                        {
                            ProductID = 3,
                            Description = "Product 3 Description",
                            Name = "Product 3",
                            Price = 91083m
                        },
                        new
                        {
                            ProductID = 4,
                            Description = "Product 4 Description",
                            Name = "Product 4",
                            Price = 59381m
                        },
                        new
                        {
                            ProductID = 5,
                            Description = "Product 5 Description",
                            Name = "Product 5",
                            Price = 90845m
                        },
                        new
                        {
                            ProductID = 6,
                            Description = "Product 6 Description",
                            Name = "Product 6",
                            Price = 21308m
                        },
                        new
                        {
                            ProductID = 7,
                            Description = "Product 7 Description",
                            Name = "Product 7",
                            Price = 90089m
                        },
                        new
                        {
                            ProductID = 8,
                            Description = "Product 8 Description",
                            Name = "Product 8",
                            Price = 78976m
                        },
                        new
                        {
                            ProductID = 9,
                            Description = "Product 9 Description",
                            Name = "Product 9",
                            Price = 18782m
                        },
                        new
                        {
                            ProductID = 10,
                            Description = "Product 10 Description",
                            Name = "Product 10",
                            Price = 53864m
                        },
                        new
                        {
                            ProductID = 11,
                            Description = "Product 11 Description",
                            Name = "Product 11",
                            Price = 34089m
                        },
                        new
                        {
                            ProductID = 12,
                            Description = "Product 12 Description",
                            Name = "Product 12",
                            Price = 45424m
                        },
                        new
                        {
                            ProductID = 13,
                            Description = "Product 13 Description",
                            Name = "Product 13",
                            Price = 86683m
                        },
                        new
                        {
                            ProductID = 14,
                            Description = "Product 14 Description",
                            Name = "Product 14",
                            Price = 69309m
                        },
                        new
                        {
                            ProductID = 15,
                            Description = "Product 15 Description",
                            Name = "Product 15",
                            Price = 94031m
                        },
                        new
                        {
                            ProductID = 16,
                            Description = "Product 16 Description",
                            Name = "Product 16",
                            Price = 64637m
                        },
                        new
                        {
                            ProductID = 17,
                            Description = "Product 17 Description",
                            Name = "Product 17",
                            Price = 17380m
                        },
                        new
                        {
                            ProductID = 18,
                            Description = "Product 18 Description",
                            Name = "Product 18",
                            Price = 74852m
                        },
                        new
                        {
                            ProductID = 19,
                            Description = "Product 19 Description",
                            Name = "Product 19",
                            Price = 27848m
                        },
                        new
                        {
                            ProductID = 20,
                            Description = "Product 20 Description",
                            Name = "Product 20",
                            Price = 83458m
                        },
                        new
                        {
                            ProductID = 21,
                            Description = "Product 21 Description",
                            Name = "Product 21",
                            Price = 53758m
                        },
                        new
                        {
                            ProductID = 22,
                            Description = "Product 22 Description",
                            Name = "Product 22",
                            Price = 87159m
                        },
                        new
                        {
                            ProductID = 23,
                            Description = "Product 23 Description",
                            Name = "Product 23",
                            Price = 17553m
                        },
                        new
                        {
                            ProductID = 24,
                            Description = "Product 24 Description",
                            Name = "Product 24",
                            Price = 99425m
                        },
                        new
                        {
                            ProductID = 25,
                            Description = "Product 25 Description",
                            Name = "Product 25",
                            Price = 80598m
                        },
                        new
                        {
                            ProductID = 26,
                            Description = "Product 26 Description",
                            Name = "Product 26",
                            Price = 58025m
                        },
                        new
                        {
                            ProductID = 27,
                            Description = "Product 27 Description",
                            Name = "Product 27",
                            Price = 13002m
                        },
                        new
                        {
                            ProductID = 28,
                            Description = "Product 28 Description",
                            Name = "Product 28",
                            Price = 52639m
                        },
                        new
                        {
                            ProductID = 29,
                            Description = "Product 29 Description",
                            Name = "Product 29",
                            Price = 15487m
                        },
                        new
                        {
                            ProductID = 30,
                            Description = "Product 30 Description",
                            Name = "Product 30",
                            Price = 22110m
                        },
                        new
                        {
                            ProductID = 31,
                            Description = "Product 31 Description",
                            Name = "Product 31",
                            Price = 69664m
                        },
                        new
                        {
                            ProductID = 32,
                            Description = "Product 32 Description",
                            Name = "Product 32",
                            Price = 13539m
                        },
                        new
                        {
                            ProductID = 33,
                            Description = "Product 33 Description",
                            Name = "Product 33",
                            Price = 52927m
                        },
                        new
                        {
                            ProductID = 34,
                            Description = "Product 34 Description",
                            Name = "Product 34",
                            Price = 53365m
                        },
                        new
                        {
                            ProductID = 35,
                            Description = "Product 35 Description",
                            Name = "Product 35",
                            Price = 39921m
                        },
                        new
                        {
                            ProductID = 36,
                            Description = "Product 36 Description",
                            Name = "Product 36",
                            Price = 64544m
                        },
                        new
                        {
                            ProductID = 37,
                            Description = "Product 37 Description",
                            Name = "Product 37",
                            Price = 98684m
                        },
                        new
                        {
                            ProductID = 38,
                            Description = "Product 38 Description",
                            Name = "Product 38",
                            Price = 79085m
                        },
                        new
                        {
                            ProductID = 39,
                            Description = "Product 39 Description",
                            Name = "Product 39",
                            Price = 64675m
                        },
                        new
                        {
                            ProductID = 40,
                            Description = "Product 40 Description",
                            Name = "Product 40",
                            Price = 13268m
                        },
                        new
                        {
                            ProductID = 41,
                            Description = "Product 41 Description",
                            Name = "Product 41",
                            Price = 51817m
                        },
                        new
                        {
                            ProductID = 42,
                            Description = "Product 42 Description",
                            Name = "Product 42",
                            Price = 64637m
                        },
                        new
                        {
                            ProductID = 43,
                            Description = "Product 43 Description",
                            Name = "Product 43",
                            Price = 84785m
                        },
                        new
                        {
                            ProductID = 44,
                            Description = "Product 44 Description",
                            Name = "Product 44",
                            Price = 85767m
                        },
                        new
                        {
                            ProductID = 45,
                            Description = "Product 45 Description",
                            Name = "Product 45",
                            Price = 79484m
                        },
                        new
                        {
                            ProductID = 46,
                            Description = "Product 46 Description",
                            Name = "Product 46",
                            Price = 77988m
                        },
                        new
                        {
                            ProductID = 47,
                            Description = "Product 47 Description",
                            Name = "Product 47",
                            Price = 19654m
                        },
                        new
                        {
                            ProductID = 48,
                            Description = "Product 48 Description",
                            Name = "Product 48",
                            Price = 52038m
                        },
                        new
                        {
                            ProductID = 49,
                            Description = "Product 49 Description",
                            Name = "Product 49",
                            Price = 17255m
                        },
                        new
                        {
                            ProductID = 50,
                            Description = "Product 50 Description",
                            Name = "Product 50",
                            Price = 40224m
                        },
                        new
                        {
                            ProductID = 51,
                            Description = "Product 51 Description",
                            Name = "Product 51",
                            Price = 95083m
                        },
                        new
                        {
                            ProductID = 52,
                            Description = "Product 52 Description",
                            Name = "Product 52",
                            Price = 71817m
                        },
                        new
                        {
                            ProductID = 53,
                            Description = "Product 53 Description",
                            Name = "Product 53",
                            Price = 95006m
                        },
                        new
                        {
                            ProductID = 54,
                            Description = "Product 54 Description",
                            Name = "Product 54",
                            Price = 30227m
                        },
                        new
                        {
                            ProductID = 55,
                            Description = "Product 55 Description",
                            Name = "Product 55",
                            Price = 48143m
                        },
                        new
                        {
                            ProductID = 56,
                            Description = "Product 56 Description",
                            Name = "Product 56",
                            Price = 74090m
                        },
                        new
                        {
                            ProductID = 57,
                            Description = "Product 57 Description",
                            Name = "Product 57",
                            Price = 81890m
                        },
                        new
                        {
                            ProductID = 58,
                            Description = "Product 58 Description",
                            Name = "Product 58",
                            Price = 91657m
                        },
                        new
                        {
                            ProductID = 59,
                            Description = "Product 59 Description",
                            Name = "Product 59",
                            Price = 78782m
                        },
                        new
                        {
                            ProductID = 60,
                            Description = "Product 60 Description",
                            Name = "Product 60",
                            Price = 42819m
                        },
                        new
                        {
                            ProductID = 61,
                            Description = "Product 61 Description",
                            Name = "Product 61",
                            Price = 18305m
                        },
                        new
                        {
                            ProductID = 62,
                            Description = "Product 62 Description",
                            Name = "Product 62",
                            Price = 47449m
                        },
                        new
                        {
                            ProductID = 63,
                            Description = "Product 63 Description",
                            Name = "Product 63",
                            Price = 73488m
                        },
                        new
                        {
                            ProductID = 64,
                            Description = "Product 64 Description",
                            Name = "Product 64",
                            Price = 96671m
                        },
                        new
                        {
                            ProductID = 65,
                            Description = "Product 65 Description",
                            Name = "Product 65",
                            Price = 84200m
                        },
                        new
                        {
                            ProductID = 66,
                            Description = "Product 66 Description",
                            Name = "Product 66",
                            Price = 30550m
                        },
                        new
                        {
                            ProductID = 67,
                            Description = "Product 67 Description",
                            Name = "Product 67",
                            Price = 92496m
                        },
                        new
                        {
                            ProductID = 68,
                            Description = "Product 68 Description",
                            Name = "Product 68",
                            Price = 43317m
                        },
                        new
                        {
                            ProductID = 69,
                            Description = "Product 69 Description",
                            Name = "Product 69",
                            Price = 39388m
                        },
                        new
                        {
                            ProductID = 70,
                            Description = "Product 70 Description",
                            Name = "Product 70",
                            Price = 39487m
                        },
                        new
                        {
                            ProductID = 71,
                            Description = "Product 71 Description",
                            Name = "Product 71",
                            Price = 65953m
                        },
                        new
                        {
                            ProductID = 72,
                            Description = "Product 72 Description",
                            Name = "Product 72",
                            Price = 38295m
                        },
                        new
                        {
                            ProductID = 73,
                            Description = "Product 73 Description",
                            Name = "Product 73",
                            Price = 20176m
                        },
                        new
                        {
                            ProductID = 74,
                            Description = "Product 74 Description",
                            Name = "Product 74",
                            Price = 24579m
                        },
                        new
                        {
                            ProductID = 75,
                            Description = "Product 75 Description",
                            Name = "Product 75",
                            Price = 41641m
                        },
                        new
                        {
                            ProductID = 76,
                            Description = "Product 76 Description",
                            Name = "Product 76",
                            Price = 89120m
                        },
                        new
                        {
                            ProductID = 77,
                            Description = "Product 77 Description",
                            Name = "Product 77",
                            Price = 12374m
                        },
                        new
                        {
                            ProductID = 78,
                            Description = "Product 78 Description",
                            Name = "Product 78",
                            Price = 31786m
                        },
                        new
                        {
                            ProductID = 79,
                            Description = "Product 79 Description",
                            Name = "Product 79",
                            Price = 29940m
                        },
                        new
                        {
                            ProductID = 80,
                            Description = "Product 80 Description",
                            Name = "Product 80",
                            Price = 12609m
                        },
                        new
                        {
                            ProductID = 81,
                            Description = "Product 81 Description",
                            Name = "Product 81",
                            Price = 48371m
                        },
                        new
                        {
                            ProductID = 82,
                            Description = "Product 82 Description",
                            Name = "Product 82",
                            Price = 60964m
                        },
                        new
                        {
                            ProductID = 83,
                            Description = "Product 83 Description",
                            Name = "Product 83",
                            Price = 45383m
                        },
                        new
                        {
                            ProductID = 84,
                            Description = "Product 84 Description",
                            Name = "Product 84",
                            Price = 75263m
                        },
                        new
                        {
                            ProductID = 85,
                            Description = "Product 85 Description",
                            Name = "Product 85",
                            Price = 27027m
                        },
                        new
                        {
                            ProductID = 86,
                            Description = "Product 86 Description",
                            Name = "Product 86",
                            Price = 97846m
                        },
                        new
                        {
                            ProductID = 87,
                            Description = "Product 87 Description",
                            Name = "Product 87",
                            Price = 18533m
                        },
                        new
                        {
                            ProductID = 88,
                            Description = "Product 88 Description",
                            Name = "Product 88",
                            Price = 32699m
                        },
                        new
                        {
                            ProductID = 89,
                            Description = "Product 89 Description",
                            Name = "Product 89",
                            Price = 15222m
                        },
                        new
                        {
                            ProductID = 90,
                            Description = "Product 90 Description",
                            Name = "Product 90",
                            Price = 65830m
                        },
                        new
                        {
                            ProductID = 91,
                            Description = "Product 91 Description",
                            Name = "Product 91",
                            Price = 82654m
                        },
                        new
                        {
                            ProductID = 92,
                            Description = "Product 92 Description",
                            Name = "Product 92",
                            Price = 17026m
                        },
                        new
                        {
                            ProductID = 93,
                            Description = "Product 93 Description",
                            Name = "Product 93",
                            Price = 10302m
                        },
                        new
                        {
                            ProductID = 94,
                            Description = "Product 94 Description",
                            Name = "Product 94",
                            Price = 31855m
                        },
                        new
                        {
                            ProductID = 95,
                            Description = "Product 95 Description",
                            Name = "Product 95",
                            Price = 94962m
                        },
                        new
                        {
                            ProductID = 96,
                            Description = "Product 96 Description",
                            Name = "Product 96",
                            Price = 14367m
                        },
                        new
                        {
                            ProductID = 97,
                            Description = "Product 97 Description",
                            Name = "Product 97",
                            Price = 91148m
                        },
                        new
                        {
                            ProductID = 98,
                            Description = "Product 98 Description",
                            Name = "Product 98",
                            Price = 88113m
                        },
                        new
                        {
                            ProductID = 99,
                            Description = "Product 99 Description",
                            Name = "Product 99",
                            Price = 11566m
                        },
                        new
                        {
                            ProductID = 100,
                            Description = "Product 100 Description",
                            Name = "Product 100",
                            Price = 58934m
                        });
                });

            modelBuilder.Entity("Catalog.Domain.ProductInStock", b =>
                {
                    b.Property<int>("ProductInStockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ProductInStockId");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            ProductInStockId = 1,
                            ProductId = 1,
                            Stock = 78
                        },
                        new
                        {
                            ProductInStockId = 2,
                            ProductId = 2,
                            Stock = 41
                        },
                        new
                        {
                            ProductInStockId = 3,
                            ProductId = 3,
                            Stock = 86
                        },
                        new
                        {
                            ProductInStockId = 4,
                            ProductId = 4,
                            Stock = 3
                        },
                        new
                        {
                            ProductInStockId = 5,
                            ProductId = 5,
                            Stock = 20
                        },
                        new
                        {
                            ProductInStockId = 6,
                            ProductId = 6,
                            Stock = 0
                        },
                        new
                        {
                            ProductInStockId = 7,
                            ProductId = 7,
                            Stock = 91
                        },
                        new
                        {
                            ProductInStockId = 8,
                            ProductId = 8,
                            Stock = 65
                        },
                        new
                        {
                            ProductInStockId = 9,
                            ProductId = 9,
                            Stock = 0
                        },
                        new
                        {
                            ProductInStockId = 10,
                            ProductId = 10,
                            Stock = 4
                        },
                        new
                        {
                            ProductInStockId = 11,
                            ProductId = 11,
                            Stock = 90
                        },
                        new
                        {
                            ProductInStockId = 12,
                            ProductId = 12,
                            Stock = 51
                        },
                        new
                        {
                            ProductInStockId = 13,
                            ProductId = 13,
                            Stock = 53
                        },
                        new
                        {
                            ProductInStockId = 14,
                            ProductId = 14,
                            Stock = 75
                        },
                        new
                        {
                            ProductInStockId = 15,
                            ProductId = 15,
                            Stock = 33
                        },
                        new
                        {
                            ProductInStockId = 16,
                            ProductId = 16,
                            Stock = 66
                        },
                        new
                        {
                            ProductInStockId = 17,
                            ProductId = 17,
                            Stock = 23
                        },
                        new
                        {
                            ProductInStockId = 18,
                            ProductId = 18,
                            Stock = 29
                        },
                        new
                        {
                            ProductInStockId = 19,
                            ProductId = 19,
                            Stock = 50
                        },
                        new
                        {
                            ProductInStockId = 20,
                            ProductId = 20,
                            Stock = 27
                        },
                        new
                        {
                            ProductInStockId = 21,
                            ProductId = 21,
                            Stock = 52
                        },
                        new
                        {
                            ProductInStockId = 22,
                            ProductId = 22,
                            Stock = 12
                        },
                        new
                        {
                            ProductInStockId = 23,
                            ProductId = 23,
                            Stock = 69
                        },
                        new
                        {
                            ProductInStockId = 24,
                            ProductId = 24,
                            Stock = 74
                        },
                        new
                        {
                            ProductInStockId = 25,
                            ProductId = 25,
                            Stock = 7
                        },
                        new
                        {
                            ProductInStockId = 26,
                            ProductId = 26,
                            Stock = 29
                        },
                        new
                        {
                            ProductInStockId = 27,
                            ProductId = 27,
                            Stock = 24
                        },
                        new
                        {
                            ProductInStockId = 28,
                            ProductId = 28,
                            Stock = 21
                        },
                        new
                        {
                            ProductInStockId = 29,
                            ProductId = 29,
                            Stock = 61
                        },
                        new
                        {
                            ProductInStockId = 30,
                            ProductId = 30,
                            Stock = 63
                        },
                        new
                        {
                            ProductInStockId = 31,
                            ProductId = 31,
                            Stock = 62
                        },
                        new
                        {
                            ProductInStockId = 32,
                            ProductId = 32,
                            Stock = 56
                        },
                        new
                        {
                            ProductInStockId = 33,
                            ProductId = 33,
                            Stock = 17
                        },
                        new
                        {
                            ProductInStockId = 34,
                            ProductId = 34,
                            Stock = 36
                        },
                        new
                        {
                            ProductInStockId = 35,
                            ProductId = 35,
                            Stock = 62
                        },
                        new
                        {
                            ProductInStockId = 36,
                            ProductId = 36,
                            Stock = 35
                        },
                        new
                        {
                            ProductInStockId = 37,
                            ProductId = 37,
                            Stock = 40
                        },
                        new
                        {
                            ProductInStockId = 38,
                            ProductId = 38,
                            Stock = 4
                        },
                        new
                        {
                            ProductInStockId = 39,
                            ProductId = 39,
                            Stock = 24
                        },
                        new
                        {
                            ProductInStockId = 40,
                            ProductId = 40,
                            Stock = 37
                        },
                        new
                        {
                            ProductInStockId = 41,
                            ProductId = 41,
                            Stock = 65
                        },
                        new
                        {
                            ProductInStockId = 42,
                            ProductId = 42,
                            Stock = 23
                        },
                        new
                        {
                            ProductInStockId = 43,
                            ProductId = 43,
                            Stock = 40
                        },
                        new
                        {
                            ProductInStockId = 44,
                            ProductId = 44,
                            Stock = 21
                        },
                        new
                        {
                            ProductInStockId = 45,
                            ProductId = 45,
                            Stock = 38
                        },
                        new
                        {
                            ProductInStockId = 46,
                            ProductId = 46,
                            Stock = 75
                        },
                        new
                        {
                            ProductInStockId = 47,
                            ProductId = 47,
                            Stock = 24
                        },
                        new
                        {
                            ProductInStockId = 48,
                            ProductId = 48,
                            Stock = 82
                        },
                        new
                        {
                            ProductInStockId = 49,
                            ProductId = 49,
                            Stock = 87
                        },
                        new
                        {
                            ProductInStockId = 50,
                            ProductId = 50,
                            Stock = 42
                        },
                        new
                        {
                            ProductInStockId = 51,
                            ProductId = 51,
                            Stock = 30
                        },
                        new
                        {
                            ProductInStockId = 52,
                            ProductId = 52,
                            Stock = 93
                        },
                        new
                        {
                            ProductInStockId = 53,
                            ProductId = 53,
                            Stock = 2
                        },
                        new
                        {
                            ProductInStockId = 54,
                            ProductId = 54,
                            Stock = 87
                        },
                        new
                        {
                            ProductInStockId = 55,
                            ProductId = 55,
                            Stock = 84
                        },
                        new
                        {
                            ProductInStockId = 56,
                            ProductId = 56,
                            Stock = 65
                        },
                        new
                        {
                            ProductInStockId = 57,
                            ProductId = 57,
                            Stock = 72
                        },
                        new
                        {
                            ProductInStockId = 58,
                            ProductId = 58,
                            Stock = 11
                        },
                        new
                        {
                            ProductInStockId = 59,
                            ProductId = 59,
                            Stock = 95
                        },
                        new
                        {
                            ProductInStockId = 60,
                            ProductId = 60,
                            Stock = 91
                        },
                        new
                        {
                            ProductInStockId = 61,
                            ProductId = 61,
                            Stock = 76
                        },
                        new
                        {
                            ProductInStockId = 62,
                            ProductId = 62,
                            Stock = 69
                        },
                        new
                        {
                            ProductInStockId = 63,
                            ProductId = 63,
                            Stock = 4
                        },
                        new
                        {
                            ProductInStockId = 64,
                            ProductId = 64,
                            Stock = 36
                        },
                        new
                        {
                            ProductInStockId = 65,
                            ProductId = 65,
                            Stock = 41
                        },
                        new
                        {
                            ProductInStockId = 66,
                            ProductId = 66,
                            Stock = 33
                        },
                        new
                        {
                            ProductInStockId = 67,
                            ProductId = 67,
                            Stock = 33
                        },
                        new
                        {
                            ProductInStockId = 68,
                            ProductId = 68,
                            Stock = 16
                        },
                        new
                        {
                            ProductInStockId = 69,
                            ProductId = 69,
                            Stock = 13
                        },
                        new
                        {
                            ProductInStockId = 70,
                            ProductId = 70,
                            Stock = 97
                        },
                        new
                        {
                            ProductInStockId = 71,
                            ProductId = 71,
                            Stock = 25
                        },
                        new
                        {
                            ProductInStockId = 72,
                            ProductId = 72,
                            Stock = 19
                        },
                        new
                        {
                            ProductInStockId = 73,
                            ProductId = 73,
                            Stock = 4
                        },
                        new
                        {
                            ProductInStockId = 74,
                            ProductId = 74,
                            Stock = 12
                        },
                        new
                        {
                            ProductInStockId = 75,
                            ProductId = 75,
                            Stock = 61
                        },
                        new
                        {
                            ProductInStockId = 76,
                            ProductId = 76,
                            Stock = 29
                        },
                        new
                        {
                            ProductInStockId = 77,
                            ProductId = 77,
                            Stock = 72
                        },
                        new
                        {
                            ProductInStockId = 78,
                            ProductId = 78,
                            Stock = 48
                        },
                        new
                        {
                            ProductInStockId = 79,
                            ProductId = 79,
                            Stock = 36
                        },
                        new
                        {
                            ProductInStockId = 80,
                            ProductId = 80,
                            Stock = 32
                        },
                        new
                        {
                            ProductInStockId = 81,
                            ProductId = 81,
                            Stock = 4
                        },
                        new
                        {
                            ProductInStockId = 82,
                            ProductId = 82,
                            Stock = 42
                        },
                        new
                        {
                            ProductInStockId = 83,
                            ProductId = 83,
                            Stock = 34
                        },
                        new
                        {
                            ProductInStockId = 84,
                            ProductId = 84,
                            Stock = 18
                        },
                        new
                        {
                            ProductInStockId = 85,
                            ProductId = 85,
                            Stock = 33
                        },
                        new
                        {
                            ProductInStockId = 86,
                            ProductId = 86,
                            Stock = 69
                        },
                        new
                        {
                            ProductInStockId = 87,
                            ProductId = 87,
                            Stock = 54
                        },
                        new
                        {
                            ProductInStockId = 88,
                            ProductId = 88,
                            Stock = 29
                        },
                        new
                        {
                            ProductInStockId = 89,
                            ProductId = 89,
                            Stock = 51
                        },
                        new
                        {
                            ProductInStockId = 90,
                            ProductId = 90,
                            Stock = 96
                        },
                        new
                        {
                            ProductInStockId = 91,
                            ProductId = 91,
                            Stock = 63
                        },
                        new
                        {
                            ProductInStockId = 92,
                            ProductId = 92,
                            Stock = 29
                        },
                        new
                        {
                            ProductInStockId = 93,
                            ProductId = 93,
                            Stock = 9
                        },
                        new
                        {
                            ProductInStockId = 94,
                            ProductId = 94,
                            Stock = 33
                        },
                        new
                        {
                            ProductInStockId = 95,
                            ProductId = 95,
                            Stock = 60
                        },
                        new
                        {
                            ProductInStockId = 96,
                            ProductId = 96,
                            Stock = 95
                        },
                        new
                        {
                            ProductInStockId = 97,
                            ProductId = 97,
                            Stock = 18
                        },
                        new
                        {
                            ProductInStockId = 98,
                            ProductId = 98,
                            Stock = 3
                        },
                        new
                        {
                            ProductInStockId = 99,
                            ProductId = 99,
                            Stock = 79
                        },
                        new
                        {
                            ProductInStockId = 100,
                            ProductId = 100,
                            Stock = 5
                        });
                });

            modelBuilder.Entity("Catalog.Domain.ProductInStock", b =>
                {
                    b.HasOne("Catalog.Domain.Product", null)
                        .WithOne("Stock")
                        .HasForeignKey("Catalog.Domain.ProductInStock", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
